# This is a generated file. Not intended for manual editing.
services:
  dentistreservation.api:
    build:
      context: "/home/matheuscosta/RiderProjects/DentistReservation"
      dockerfile: "DentistReservation.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "dentistreservation.api:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "/home/matheuscosta/.nuget/packages:/home/app/.nuget/packages"
    - "/home/matheuscosta/RiderProjects/DentistReservation/DentistReservation.Api:/app:rw"
    - "/home/matheuscosta/RiderProjects/DentistReservation:/src:rw"
    - "/home/matheuscosta/.local/share/JetBrains/RiderRemoteDebugger/2024.1/Linux64:/opt/rider-debugger"
    - "/home/matheuscosta/Downloads/JetBrains Rider-2023.3.4/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/matheuscosta/.cache/JetBrains/Rider2024.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_26_08_34_08:/var/opt/rider-debugger:rw"
    working_dir: "/app"
