services:
  dentistreservation.api:
    image: dentistreservation.api
    restart: always
    build:
      context: .
      dockerfile: src/DentistReservation.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5002:8080
    depends_on:
      - dentistreservation.db
        
  dentistreservation.db:
    image: mysql:8.0
    restart: always
    hostname: dentistreservation.db
    environment:
      MYSQL_DATABASE: 'DentistReservation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass@word123!@#'
      MYSQL_ROOT_PASSWORD: 'pass@word123!@#'
    ports:
      - 3306:3306
    expose:
      - 3306      